---
title: "Map"
output: html_document
date: "2024-03-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#####
#install.packages("remotes")
#remotes::install_github("tylermorganwall/rayshader")
#remotes::install_github("tylermorganwall/rayimage")

library(rayshader)
library(raster)
library(osmdata)
library(sf)
library(dplyr)
library(ggplot2)
library(here)
library(elevatr)
library(sp)
```




```{r}
# Define the coordinates for Study Site
location <- "Point Fermin State Beach, Los Angeles, CA"
latitude <- 33.7056
longitude <- -118.2935
z <- 11 # scale

# Set the CRS to EPSG:4326 (WGS84)
crs <- 4326

# Buffer size for bounding box
buffer <- 0.25  # Adjust as needed

# Define the bounding box coordinates
xmin <- longitude - buffer
xmax <- longitude + buffer
ymin <- latitude - buffer
ymax <- latitude + buffer

# Define the bounding box coordinates
cropped_extent <- raster::extent(c(xmin, xmax, ymin, ymax)) %>%
  sf::st_bbox(crs = crs) %>%
  sf::st_as_sfc() %>%
  sf::st_set_crs(crs) %>%
  sf::st_bbox()

# Create a data frame with bounding box coordinates
bbox_coords <- data.frame(x = c(xmin, xmax), 
                          y = c(ymin, ymax))

bbox_sf <- st_as_sf(bbox_coords, coords = c("x", "y"), crs = crs)

# Download elevation data using the bounding box coordinates
elevation_raster <- get_elev_raster(locations = bbox_sf, crs=crs, z = z, src = "aws")

elevation_raster <- elevation_raster %>% 
  raster::crop(y = cropped_extent)

elevation_raster2 <-here::here("/Users/bobbydell/Downloads/USGS_13_n34w119_20190917.tif") %>% 
  file.path() %>% 
  raster::raster() 

elevation_raster2 <-elevation_raster2 %>% 
  raster::crop(y = cropped_extent)

raster_cutout <- raster::projectRaster(elevation_raster2, crs = "+proj=utm +zone=11 +datum=NAD83 +units=m +no_defs") 

elevation_raster3 <-here::here("/Users/bobbydell/Downloads/USGS_one_meter_x37y374_CA_LosAngeles_2016.tif") %>% 
  file.path() %>% 
  raster::raster() 

elevation_raster3 <- elevation_raster3 %>%
  raster::crop(y = raster_cutout) 

elevation_raster3 <- raster::projectRaster(elevation_raster2, crs = "+proj=latlon +datum=WGS84 +units=m +no_defs") 

elevation_raster
elevation_raster2
elevation_raster3

# Resample raster layer 2 to have the same extent and resolution
resampled_elevation_raster2 <- resample(elevation_raster2, elevation_raster, method = "ngb")

# Resample raster layer 3 using nearest-neighbor resampling
resampled_elevation_raster3 <- resample(elevation_raster3, elevation_raster, method = "ngb") # nearest neighbor sampling for higher resolution

# Convert resampled raster layers to matrices
elevation_matrix <- as.matrix(elevation_raster)
elevation_matrix2 <- as.matrix(resampled_elevation_raster2)
elevation_matrix3 <- as.matrix(resampled_elevation_raster3)

# Check dimensions of each matrix
dim1 <- dim(elevation_matrix)
dim2 <- dim(elevation_matrix2)
dim3 <- dim(elevation_matrix3)

# Check if dimensions match
if (identical(dim1, dim2) && identical(dim1, dim3)) {
  # Calculate the mean of corresponding elements in the matrices
  mean_matrix <- (elevation_matrix + elevation_matrix2 + elevation_matrix3) / 3
} else {
  print("Dimensions of matrices do not match. Cannot calculate mean.")
}

mean_matrix %>% 
  rayshader::height_shade() %>% 
  rayshader::plot_map()
```




```{r}
library(magick)
# set missing values to -1 (assume this is water)
mean_matrix[is.na(mean_matrix)] <- -1

# Calculate the range of elevation values in the mean matrix
elevation_range <- range(mean_matrix)

# Calculate the difference between the minimum and maximum elevation values
elevation_difference <- elevation_range[2] - elevation_range[1]

# Calculate the vertical exaggeration factor (z-scale)
zscale_scaling_factor <- 1
estimated_zscale <- zscale_scaling_factor * elevation_difference
```


```{r}
base_map<- mean_matrix %>%
  rayshader::height_shade() %>%
  rayshader::add_overlay(rayshader::sphere_shade(mean_matrix, colorintensity = 5),
                         alphalayer = 0.5)  %>%
  rayshader::add_overlay(
    rayshader::sphere_shade(elevation_matrix2,
                            texture = "desert",
                            colorintensity = 5),
    alphalayer = 0.5
  ) %>%
  rayshader::add_shadow(rayshader::lamb_shade(mean_matrix), 0) %>%
  rayshader::add_shadow(rayshader::ambient_shade(mean_matrix), 0) %>%
  rayshader::add_shadow(
    rayshader::texture_shade(
      mean_matrix,
      detail = 8 / 10,
      contrast = 9,
      brightness = 11
    ),
    0.1
  ) 
```
```{r}
base_map %>% 
  rayshader::plot_3d(heightmap = mean_matrix, 
                     zscale = 5, fov = 0, 
                     theta = -45, zoom = 0.75, phi = 45,
                     water = TRUE, waterdepth = 4, 
                     wateralpha = 0.4, watercolor = "cyan2",
                     waterlinecolor = "white", waterlinealpha = 0.5,
                     background = "white")

# Create 2D snapshot of 3D rendering
rayshader::render_snapshot()
```

```{r}
#osm overlays

bbox_long_lat <- sf::st_bbox(cropped_raster) %>%
  sf::st_as_sfc() %>%
  sf::st_transform(crs = 4326) %>%
  sf::st_bbox()

# get highways
bourtange_footways <- osmdata::opq(bbox_long_lat) %>%
  osmdata::add_osm_feature("highway") %>%
  osmdata::osmdata_sf()

footway_geom <- bourtange_footways$osm_lines %>%
  sf::st_transform(crs = raster_crs)

footway_overlay <- footway_geom %>%
  rayshader::generate_line_overlay(
    extent = cropped_extent,
    heightmap = raster_matrix,
    color = "gainsboro",
    linewidth = 2
  )

# get trees
bourtange_trees <- osmdata::opq(bbox_long_lat) %>%
  osmdata::add_osm_feature("landuse", "forest") %>%
  osmdata::osmdata_sf()

trees_geom <- bourtange_trees$osm_polygons %>%
  sf::st_transform(crs = raster_crs)

tree_overlay <- trees_geom %>%
  rayshader::generate_line_overlay(extent = cropped_extent,
                                   heightmap = raster_matrix,
                                   color = "darkolivegreen")

# get grassy areas
bourtange_grass <- osmdata::opq(bbox_long_lat) %>%
  osmdata::add_osm_feature("landuse", "grass") %>%
  osmdata::osmdata_sf()

grass_geom <- bourtange_grass$osm_polygons %>%
  sf::st_transform(crs = raster_crs)

grass_overlay <- grass_geom %>%
  rayshader::generate_line_overlay(extent = cropped_extent,
                                   heightmap = raster_matrix,
                                   color = "darkolivegreen")

# get buildings
bourtange_buildings <- osmdata::opq(bbox_long_lat) %>%
  osmdata::add_osm_feature("building") %>%
  osmdata::osmdata_sf()

buildings_geom <- bourtange_buildings$osm_polygons  %>%
  sf::st_transform(crs = raster_crs)

building_overlay <- buildings_geom %>%
  rayshader::generate_polygon_overlay(extent = cropped_extent,
                                      heightmap = raster_matrix,
                                      palette = "sienna1")

# get windmill
windmill <- osmdata::opq(bbox_long_lat) %>%
  osmdata::add_osm_feature("man_made", "windmill") %>%
  osmdata::osmdata_sf()

windmill_geom <- windmill$osm_polygons  %>%
  sf::st_transform(crs = raster_crs)

windmill_overlay <- windmill_geom %>%
  rayshader::generate_polygon_overlay(extent = cropped_extent,
                                      heightmap = raster_matrix,
                                      palette = "darkgrey")

```
```{r}
base_map %>%
  rayshader::add_overlay(overlay = footway_overlay, alphalayer = 0.95) %>%
  rayshader::add_overlay(overlay = building_overlay, alphalayer = 0.75) %>%
  rayshader::add_overlay(overlay = tree_overlay, alphalayer = 0.6) %>%
  rayshader::add_overlay(overlay = grass_overlay, alphalayer = 0.6) %>%
  rayshader::add_overlay(overlay = windmill_overlay, alphalayer = 0.85) %>%
  rayshader::plot_3d(
    raster_matrix,
    water = TRUE,
    watercolor = "dodgerblue",
    windowsize = c(1200, 1200),
    zscale = estimated_zscale
  )

rayshader::render_camera(theta = 0, phi = 89.999, zoom = 0.75) # setting phi = 90 seems to cause problems for rayshader?

rayshader::render_highquality(
  filename = "bourtange_overhead.png",
  lightaltitude = c(22.5, 75),
  lightintensity = c(1000, 200),
  lightdirection = c(250, 0),
  print_scene_info = TRUE,
  samples = 100,
  parallel = TRUE,
  min_variance = 0,
  verbose = TRUE
)
rgl::rgl.close()
```

