---
title: "Herbivory Consumption Script"
author: "Robert Dellinger"
date: "12/1/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


if(!require(devtools)) install.packages("devtools")
#devtools::install_github("cardiomoon/predict3d")
#devtools::install_github("dill/beyonce")

library(beyonce)
require(predict3d)
require(rgl)
library(tidyverse)
library(lubridate)
library(here)
library(magrittr)
library(prophet)
library(ggiraph)
require(plyr)
library(ggiraphExtra)
library(ggExtra)
library(ggpmisc)
library(plotrix)
library(lme4)
library(hms)      
library(chron)   


```

#Loading in Data

```{r}

#reading in data 

algae.data <- read_csv(here::here("Experiment_Data", "Herbivory_Data", "Algae_Spreadsheet.csv"))
#algae.data %>% view()

algae.drying.rates <- read_csv(here::here("Experiment_Data", "Herbivory_Data", "Algae_Drying_Weights.csv"))
#algae.drying.rates %>% view()

TreatmentMeta <- read_csv(here::here("Experiment_Data", "Snail_Metadata","Treatment_Organism_ID_Information.csv"))


#insert blotted weight normalization for data 
```
#Cleaning Data
```{r, message=FALSE, warning=FALSE, fig.align='center'}

algae.drying.rates.pivoted <- algae.drying.rates %>% 
  dplyr::mutate(across(4:ncol(algae.drying.rates), ~  . -Tray_Weight)) %>% #subtracting tray weihgt from data
  arrange(Kelp_Tray_0_min) %>%#arranging by weight
  dplyr::select(Tray_ID, Treatment, Kelp_Tray_0_min:Kelp_Tray_180_min) %>%  #selecting for columns
  pivot_longer(Kelp_Tray_0_min:Kelp_Tray_180_min, values_to = "Kelp_Weight", names_to = "Time") #pivoting

algae.drying.rates.times <- algae.drying.rates.pivoted %>%
  mutate(Time = as.numeric(gsub("[^0-9]","",Time))*60, #extracting time from characters
         Tray_ID = as.character(sprintf("%02d",Tray_ID))) %>% 
  mutate(Minutes = sprintf("%02d", minute(seconds_to_period(Time))), #getting hours mintues and seconds data
         Hours = paste0(sep = "0", hour(seconds_to_period(Time))),
         Time = paste0(Hours, sep = ":", Minutes,":00")) #converting to time format

#converting weight change and time change to delta time and delta wight in order to calculate rate per minute of weight loss 
algae.drying.rates.clean <- algae.drying.rates.times %>% 
  dplyr::select(Tray_ID, Treatment, Kelp_Weight, Time) %>% #selecting
  mutate(Time=(hour(as_hms(Time))*60)+(minute(as_hms(Time))),
         Tray_ID=as.factor(Tray_ID)) %>% 
  arrange(Tray_ID) %>% #weight and time change (delta) per tray with leading 0 
  mutate(Weight_Change_Diff = ave(Kelp_Weight, factor(Tray_ID), FUN=function(x) c(0, diff(x))),
         Time_Change_Diff = ave(Time, factor(Tray_ID), FUN=function(x) c(0, diff(x))),
         Weight_Change_Rate=Weight_Change_Diff/Time_Change_Diff) %>% 
  mutate_all(~replace(., is.nan(.), 0))
    
#delta weight over time figure
ggplot(algae.drying.rates.clean, aes(x=Time, y=Weight_Change_Diff,
       group=Tray_ID, fill=Tray_ID, color=Tray_ID)) +
  geom_point(size = 3, shape = 20)+ #adding points
  geom_line(method="lm",size = 1, alpha=0.25)+ #linear model
  theme(text = element_text(size = 3), axis.text.x = element_text(size = 1),#clearing x axis labels 
        legend.position="none")+ theme_minimal()
#delta weight is a funciton of time over weight ??
```



#Visualizing Individual and Multiple Linear Regressions 


```{r, message=FALSE}


#visualizing linear regression and the histogram of the data 
ggmarginalplot <-ggplot(algae.drying.rates.clean, aes(x=Time, y=Kelp_Weight)) +
  geom_point(size = 3, shape = 20, color='darkcyan')+ #adding points
  geom_smooth(method="lm",size = 1, alpha=0.25, color='darkcyan')+ #linear model
  stat_poly_eq(aes(label = paste(..eq.label.., ..rr.label.., sep = "~~~")),
             parse = TRUE, label.y = 0.95, size =4, color='darkcyan') + #adding R^2 value
  theme(text = element_text(size = 9), axis.text.x = element_text(size = 4),#clearing x axis labels 
        legend.position="none") + theme_minimal() #removing legend

ggMarginal(ggmarginalplot, margins = "y", type = "histogram", fill='darkcyan')

#visualizing linear regression between treatments
ggplot(algae.drying.rates.clean, aes(x=Time, y=Kelp_Weight,
       group=Treatment, fill=Treatment, color=Treatment)) +
  geom_point(size = 3, shape = 20)+ #adding points
  geom_smooth(method="lm",size = 1, alpha=0.25)+ #linear model
  stat_poly_eq(aes(label = paste(..eq.label.., ..rr.label.., sep = "~~~")),
             parse = TRUE, label.y = 0.95, size =3) + #adding R^2 value
  theme(text = element_text(size = 10), axis.text.x = element_text(size = 5),#clearing x axis labels 
        legend.position="none")+ theme_minimal() + #removing legend
  facet_wrap(~Treatment) #making a plot for each individual line

#visualzing differences between size classes
weight.sizes <- algae.drying.rates.clean %>%
  filter(Time=="0", ) %>% 
  dplyr::mutate(size=case_when((Kelp_Weight) <= 1 ~ "small",
                        (Kelp_Weight) > 1 & (Kelp_Weight) < 1.5 ~ "medium",
                        (Kelp_Weight) >= 1.5 ~ "large")) %>% 
  select(Tray_ID, size)
  
sized.algae.drying.rates.clean <- left_join(weight.sizes, algae.drying.rates.clean)

ggplot(sized.algae.drying.rates.clean, aes(x=Time, y=Kelp_Weight,
       group=size, fill=size, color=size)) +
  geom_point(size = 3, shape = 20)+ #adding points
  geom_smooth(method="lm",size = 1, alpha=0.25)+ #linear model
  stat_poly_eq(aes(label = paste(..eq.label.., ..rr.label.., sep = "~~~")),
             parse = TRUE, label.y = 0.95, size =3) + #adding R^2 value
  scale_color_manual(values = beyonce_palette(18)) +
  scale_fill_manual(values = beyonce_palette(18)) +
  theme(text = element_text(size = 3), axis.text.x = element_text(size = 1),#clearing x axis labels 
        legend.position="none")+ theme_minimal()+ #removing legend
  facet_wrap(~size) #making a plot for each individual line

#make y a difference in weight use the .dif function 
#mkae initial weight a covariate in the function 


#plot visualizing the rate of change in kelp weights over time with a linear regression for each kelp disk
ggplot(algae.drying.rates.clean, aes(x = Time, y = Kelp_Weight, group=Tray_ID, fill=Tray_ID, color=Tray_ID)) +
  geom_point(size = 1, shape = 20)+ #adding points
  stat_poly_eq(aes(label = paste(..eq.label.., ..rr.label.., sep = "~~~")),
             parse = TRUE, label.y = 0.9, size =1.75) + #adding R^2 value
  geom_smooth(method="lm",size = 0.25, alpha=0.25)+ #linear model
  theme(text = element_text(size = 10), axis.text.x = element_blank(),#clearing x axis labels 
        legend.position="none")+ #removing legend
  theme_minimal()+
  facet_wrap(~Tray_ID) #making a plot for each individual line

# Preparing data for linear regression
drying.rates.lm <- algae.drying.rates.clean %>% 
  mutate(Tray_ID=as.character(Tray_ID))#time to minutes

#creating a linear multiple regression model to account for the effects between kelp and time
kelp.weight.lm = lm(Kelp_Weight~Time+Tray_ID, data=drying.rates.lm)

predict3d::ggPredict(kelp.weight.lm, digits=2, mode=4, show.text=FALSE, show.error = TRUE) 

predict3d::predict3d(kelp.weight.lm, radius=0.5, xlab=NULL)
rglwidget(elementId ="1st") #3d figure (download as 3d rotational gif using movie3d())


#could normalize data as rates and then plot using a multiple regression model as a projection into time 
```


#Using linear regressions to forecast future weight

#exclude forecast apckage
```{r}

#increasing time on table in order to predict future variables
forecasted.weight.df <- drying.rates.lm %>% 
  select(Tray_ID:Time) %>% 
  group_by(Tray_ID) %>% 
  complete(Time=seq(0,300, by=10),fill=list(dummy=0)) %>% #expanding time
  ungroup()

#projections for linear model of each algal disk added to data frame
forecasted.weight.df$lm <-predict(kelp.weight.lm, forecasted.weight.df, type='response')

ggplot(forecasted.weight.df, aes(x=Time, y=lm, group=Tray_ID, fill=Tray_ID, color=Tray_ID))+
  geom_point(size = 3, shape = 20)+ #adding points
  geom_smooth(method="lm",size = 1, alpha=0.25)
  
models <- forecasted.weight.df %>% group_by(Tray_ID) %>% summarise(mod = list(kelp.weight.lm))

forecasted.weight.ts <- forecasted.weight.df %>% ts()
#normalize(forecasted.weight.ts, mode = "scale")


```


#Consumption Analysis 

```{r}

#Find a change a weight between the times 
#create a linear regression for change in weight over time to create a linear regression 
#back calcualte everything so that they are all in 0 hours 
#unblott the starting values 



#kelp weight, minutes out, simple linear egression suing delta weight (minutes as x),will calcualte change in weight since time 0 

#importing and cleaning data
algae.data.cleaned <- algae.data %>% 
  mutate(Minutes = sprintf("%02d", minute(seconds_to_period(Drying_Duration))),
         Hours=paste0("0", (hour(seconds_to_period(Drying_Duration)))),
         Time = paste0(Hours, sep = ":", Minutes, ":00")) %>% 
  mutate(Time=(hour(as_hms(Time))*60)+(minute(as_hms(Time)))) %>% 
    select(Algae_ID, Treatment_Control, Algae_Weight_Before, Algae_Weight_After, Time, Condition)

TreatmentMeta <- TreatmentMeta %>% mutate(Algae_ID = Snail_ID) %>% 
  dplyr::select(Temp_Treatment, pH_Treatment, Cage_ID, Algae_ID)

algae.treatment.data <- left_join(algae.data.cleaned, TreatmentMeta)

Algae_Weight_After_fit = lm(Algae_Weight_After ~ Time, data=algae.treatment.data)
Algae_Weight_Before_fit = lm(Algae_Weight_Before ~ Time, data=algae.treatment.data)


predict(logit, Validationdataframe, type="response")

algae.treatment.data.fit <- algae.treatment.data %>%
  mutate(Algae_Weight_Before_fit = Algae_Weight_Before_fit$fitted.values,
         Algae_Weight_After_fit = Algae_Weight_After_fit$fitted.values) %>% 
  mutate(Weight_Difference = as.numeric(Algae_Weight_Before-Algae_Weight_After)) 


autogenic.control.data<- algae.treatment.data %>% filter(Treatment_Control=='C')  %>% 
  group_by(Temp_Treatment, pH_Treatment) %>% 
  dplyr::summarize(Mean_Weight_Difference=mean(Weight_Difference),
                   SE_Weight_Difference=std.error(Weight_Difference))

#subratact the control agae weight from each indivudal kelp weight prior to finding the mean

#TINGS FOR NEXT MEETING 
#1. models for the TPC curve
#2. read about the aparametrs i need to extract 
#3. calculate the change 

  

treatment.data<- algae.treatment.data %>% filter(Treatment_Control=='T')  %>% 
  group_by(Temp_Treatment, pH_Treatment) %>% 
  dplyr::summarize(Mean_Weight_Difference=mean(Weight_Difference),
                   SE_Weight_Difference=std.error(Weight_Difference))

  
  
#Nnormalize data to gram of algae consumed per gram of organism 
  
mean.consumption.rate.data <- algae.data.corrected

```

