---
title: "Mesocosm Environmental Parameters"
output:
  pdf_document: default
  html_document: default
date: "2023-09-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(seacarb)
library(broom)
library(here)
library(lubridate)
library(ggridges)
library(dplyr)
library(ggplot2)
library(knitr)
library(ggsignif)
library(respirometry)
```


### Mesocosm Daily Check Data and pH Calculations ###

# Reading in Data for Mesocosm to Calculate pH 

```{r}
## bring in pH calibration files and raw data files
pHcalib <- read_csv(here("Data", "Mesocosm_Data", "TrispHcalibration.csv")) %>%
  mutate(TrisCalDate = ymd(TrisCalDate))

pHData <- read_csv(here("Data", "Mesocosm_Data", "Mesocosm_Daily_Datasheet.csv"))%>%
  mutate(TrisCalDate = ymd(TrisCalDate),
         Date = mdy(Date), 
         Temp_Treatment=as.factor(Temp_Treatment), 
         pH_Treatment=as.factor(pH_Treatment),
         Tank_ID=as.factor(Tank_ID)) %>% 
  select(Temp_C, mV, Salinity, TrisCalDate, Date, Tank_ID, pH_Treatment, Temp_Treatment)

# Take the tris calibration data by each date and use them to calculate pH
pHSlope <- pHcalib %>%
  group_by(TrisCalDate) %>%
  summarise(fitpH = list(lm(mVTris ~ TTris, data = cur_data()))) %>%
  mutate(tidy_fit = map(fitpH, broom::tidy)) %>%
  unnest(tidy_fit) %>%
  select(TrisCalDate, term, estimate) %>%
  pivot_wider(names_from = term, values_from = estimate)

# Calculate the pH values using the slope and intercept from the calibration data
pHjoined <- pHData %>%
  left_join(pHSlope, by = "TrisCalDate") %>%
  mutate(mVTris_calc = Temp_C * TTris + `(Intercept)`) %>%
  drop_na(Temp_C, mV)

pHcalc <- pHjoined %>%
  mutate(pH = seacarb::pH(Ex = mV, Etris = mVTris_calc, S = Salinity, T = Temp_C)) %>%
  select(Date, Tank_ID, pH_Treatment, Temp_Treatment, pH)

# Join the calculated pH values back to the mesocosm daily data
mesocosm_daily_data <- read_csv(here("Data", "Mesocosm_Data", "Mesocosm_Daily_Datasheet.csv")) %>%
  mutate(Date = mdy(Date), 
         Tank_ID = as.factor(Tank_ID), 
         pH_Treatment = as.factor(pH_Treatment), 
         Temp_Treatment = as.factor(Temp_Treatment))

final_data <- left_join(mesocosm_daily_data, pHcalc, by = c("Date", "Tank_ID", "pH_Treatment", "Temp_Treatment"))


## Write the Data
write_csv(final_data, here::here("Data", "Mesocosm_Data", "Mesocosm_pHProbe_Data_calculated.csv"))

```

# Mesocosm Daily Measurement Statistics & Figures 

# Read in TA 
```{r}
library(dplyr)

# Read in TA data for 2022-09-01
TAdata_09012022 <- read_csv(here("Data", "Mesocosm_Data", "Total_Alkalinity", "TA2022-09-01.csv")) %>% 
  mutate(Date = as.Date("2022-09-01"),
         Start_Date = as.Date("2022-08-27"),
         End_Date = as.Date("2022-09-01")) %>%
  rename(Tank_ID = SampleID) %>%
  mutate(Tank_ID = gsub("-", "_", Tank_ID),   # replace "-" with "_"
         Tank_ID = gsub("TNK_SUMP", "TNK_SMP", Tank_ID)) # replace "TNK_SUMP" with "TNK_SMP"


# Copying rows for each Tank_ID within Start_Date and End_Date
TAdata_09012022 <- TAdata_09012022 %>%
  group_by(Tank_ID) %>%
  do({
    df <- .
    dates <- seq(.$Start_Date, .$End_Date, by = "day")
    df <- df[rep(seq_len(nrow(df)), each = length(dates)), ]
    df$Date <- dates
    df
  }) %>%
  ungroup()

# Read in TA data for 2022-08-22
TAdata_08222022 <- read_csv(here("Data", "Mesocosm_Data", "Total_Alkalinity", "TA2022-08-22.csv")) %>% 
  mutate(Date = as.Date("2022-08-22"),
         Start_Date = as.Date("2022-08-22"),
         End_Date = as.Date("2022-08-26")) %>%
  rename(Tank_ID = SampleID) %>%
  mutate(Tank_ID = gsub("-", "_", Tank_ID),
         Tank_ID = gsub("TNK_SUMP", "TNK_SMP", Tank_ID))

# Copying rows for each Tank_ID within Start_Date and End_Date
TAdata_08222022 <- TAdata_08222022 %>%
  group_by(Tank_ID) %>%
  do({
    df <- .
    dates <- seq(.$Start_Date, .$End_Date, by = "day")
    df <- df[rep(seq_len(nrow(df)), each = length(dates)), ]
    df$Date <- dates
    df
  }) %>%
  ungroup()

# Read in TA data for 2022-08-16
TAdata_08162022 <- read_csv(here("Data", "Mesocosm_Data", "Total_Alkalinity", "TA2022-08-16.csv")) %>% 
  mutate(Date = as.Date("2022-08-16"),
         Start_Date = as.Date("2022-08-16"),
         End_Date = as.Date("2022-08-21")) %>%
  rename(Tank_ID = SampleID) %>%
  mutate(Tank_ID = gsub("-", "_", Tank_ID),
         Tank_ID = gsub("TNK_SUMP", "TNK_SMP", Tank_ID))

# Copying rows for each Tank_ID within Start_Date and End_Date
TAdata_08162022 <- TAdata_08162022 %>%
  group_by(Tank_ID) %>%
  do({
    df <- .
    dates <- seq(.$Start_Date, .$End_Date, by = "day")
    df <- df[rep(seq_len(nrow(df)), each = length(dates)), ]
    df$Date <- dates
    df
  }) %>%
  ungroup()

# Combine all datasets
TAdata_combined <- bind_rows(TAdata_09012022, TAdata_08222022, TAdata_08162022) %>% 
  #filter Tank_ID == CRM and Junk
  filter(Tank_ID != "CRM", Tank_ID != "Junk") %>%
  arrange(Date, Tank_ID) %>% 
  select(Date, Tank_ID, TA, TA_evap)

mesocosm.daily.data.pH <- read_csv(here("Data", "Mesocosm_Data", "Mesocosm_pHProbe_Data_calculated.csv"))

completed.mesocosm.dataset <- left_join(mesocosm.daily.data.pH, TAdata_combined, by = c("Date", "Tank_ID")) 

## Write the Data
write_csv(x = completed.mesocosm.dataset, file = here("Data", "Mesocosm_Data", "Completed_Mesocosm_Dataset_TA_pH.csv"))

```


# Calculating Carbonate Parameters

```{r}

#Reading in mesocosm in situ measurements 
mesocosm.data <- read_csv(here::here("Data", "Mesocosm_Data", "Completed_Mesocosm_Dataset_TA_pH.csv")) 

mesocosm.data <- mesocosm.data %>% 
  mutate(TA = TA * 1e-6) # Convert TA from µmol/kg to mol/kg
  
# Initialize columns for carbonate system parameters in the dataframe
mesocosm.data$pCO2 <- NA
mesocosm.data$pCO2insitu <- NA
mesocosm.data$HCO3 <- NA
mesocosm.data$CO3 <- NA
mesocosm.data$DIC <- NA

# Iterate through each row of the dataframe
for (i in 1:nrow(mesocosm.data)) {
  # Extract parameters from the current row
  pH <- mesocosm.data$pH[i] # pH value
  TA <- mesocosm.data$TA[i]  # Use the converted TA in mol/kg
  Salinity <- mesocosm.data$Salinity[i] # Assuming Salinity is in PSU
  Temp_C <- mesocosm.data$Temp_C[i]  # Temperature in degrees Celsius
  
  # Calculate carbonate system parameters using the carb function
  carbonate_params <- carb(flag = 8, var1 = pH, var2 = TA, S = Salinity, T = Temp_C, Patm = 1, P = 0, Pt = 0, Sit = 0, 
                           k1k2 = "l", kf = "pf", ks = "d", pHscale = "T", b = "u74", warn = "y")
  
  # Assign the calculated carbonate system parameters to the dataframe
  mesocosm.data$pCO2[i] <- carbonate_params$pCO2
  mesocosm.data$pCO2insitu[i] <- carbonate_params$pCO2insitu
  mesocosm.data$HCO3[i] <- carbonate_params$HCO3
  mesocosm.data$CO3[i] <- carbonate_params$CO3
  mesocosm.data$DIC[i] <- carbonate_params$DIC
}

mesocosm.data <- mesocosm.data %>% 
  mutate(TA = TA * 1e6, # Convert TA back to µmol/kg
         pCO2 = pCO2, 
         pCO2insitu = pCO2insitu,
         HCO3 = HCO3 * 1e6, # Convert HCO3 from mol/kg to µmol/kg
         CO3 = CO3 * 1e6, # Convert CO3 from mol/kg to µmol/kg
         DIC = DIC * 1e6) # Convert DIC from mol/kg to µmol/kg

print(mesocosm.data)

write_csv(mesocosm.data, here("Data", "Mesocosm_Data", "Completed_Mesocosm_Dataset_Carbonate.csv"))
```


```{r}

mesocosm.data <- read_csv(here::here("Data", "Mesocosm_Data", "Completed_Mesocosm_Dataset_Carbonate.csv"))

# Linear regression for Salinity and temperature
lm_result_temp_salinity <- lm(Salinity ~ Temp_C, data = mesocosm.data)
summary(lm_result_temp_salinity)
plot(lm_result_temp_salinity)

# Plot Temperature vs. Salinity with a linear regression line
ggplot(mesocosm.data, aes(x = Temp_C, y = Salinity)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, color="lightyellow") +
  labs(x = "Temperature (°C)", y = "Salinity (ppt)") +
  theme_minimal() +
  ggtitle("Temperature vs. Salinity")

oxygen.data <- mesocosm.data %>%
  filter(pH_Treatment != "Sump") %>% 
  select(DO_mgL, DO_Percent, Temp_C, pH_Treatment, Temp_Treatment) %>%
  na.omit()

# Linear regression for Temperature and Dissolved Oxygen
ggplot(oxygen.data, aes(x = Temp_C, y = DO_mgL, group=pH_Treatment, color=pH_Treatment)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  labs(x = "Temperature (°C)", y = "Dissolved Oxygen (mg/L)") +
  theme_minimal() +
  ggtitle("Temperature vs. Dissolved Oxygen")

# Linear regression for Temperature and Dissolved Oxygen
ggplot(oxygen.data, aes(x = Temp_C, y = DO_Percent, group=pH_Treatment, color=pH_Treatment)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  labs(x = "Temperature (°C)", y = "Dissolved Oxygen (%)") +
  theme_minimal() +
  ggtitle("Temperature vs. Dissolved Oxygen")

# Oxygen saturation linear regression
lm_result_o2_temp <- lm(DO_mgL ~ Temp_C, data = oxygen.data)
summary(lm_result_o2_temp)
plot(lm_result_o2_temp)

# Get a summary of the model
model_summary <- summary(lm_result_o2_temp)

# Access and print the R-squared value
r_squared <- model_summary$r.squared
print(paste("R-squared: DO mg/L", r_squared))

lm_result_o2_temp <- lm(DO_Percent ~ Temp_C, data = oxygen.data)
summary(lm_result_o2_temp)
plot(lm_result_o2_temp)

# Get a summary of the model
model_summary <- summary(lm_result_o2_temp)

# Access and print the R-squared value
r_squared <- model_summary$r.squared
print(paste("R-squared: DO (%)", r_squared))

```



```{r}

mesocosm.data <- read_csv(here::here("Data", "Mesocosm_Data", "Completed_Mesocosm_Dataset_Carbonate.csv"))

#summary statistics for pH by treatment
ph.means <- mesocosm.data %>%
  group_by(pH_Treatment) %>%
  dplyr::summarize(Mean_pH = mean_pH(pH, na.rm = TRUE), #used to average pH nased on H+ ions
            Sd_pH = sd(pH, na.rm = TRUE))

print(ph.means)

#summary statistics for pH by treatment
pCO2.means <- mesocosm.data %>%
  group_by(pH_Treatment) %>%
  dplyr::summarize(Mean_pCO2 = mean(pCO2, na.rm = TRUE),
            Sd_pCO2 = sd(pCO2, na.rm = TRUE))

print(pCO2.means)

# Assuming `mesocosm.data` is already loaded and you have created `ph.data` as per the previous code
ph.data <- mesocosm.data %>%
  select(pH_Treatment, pH) %>%
  filter(pH_Treatment != "Sump") # Filter out the "Sump" treatment

ph.data <- na.omit(ph.data)

# Perform t-test to compare means
t_test_result <- t.test(pH ~ pH_Treatment, data = ph.data)

# Print the t-test results
print(t_test_result)


# Calculate IQR threshold
outlier.data <- ph.data %>%
  group_by(pH_Treatment) %>%
  mutate(Q1 = quantile(pH, 0.25),
         Q3 = quantile(pH, 0.75),
         IQR = Q3 - Q1,
         Lower = Q1 - 1.5 * IQR,
         Upper = Q3 + 1.5 * IQR) %>%
  filter(pH >= Lower & pH <= Upper)

# Create a boxplot with significance annotation
# Basic plot without stat_signif
t_test_ph <- ggplot(ph.data, aes(x = pH_Treatment, y = pH, fill = pH_Treatment)) +
  scale_fill_manual(values = c("Ambient" = "darkcyan", "Low" = "cyan3"),
                    labels = c("Ambient" = "High pH", "Low" = "Low pH")) +
  geom_boxplot() +
  labs(x = "Treatment", y = "pH (total scale)", fill = "Treatment") +
  theme_classic() +
  theme(text = element_text(family = "Times New Roman", size = 12),
        axis.title = element_text(size = 12),
        legend.position = "right") +
   guides(fill = guide_legend(title = "pH Treatment"))  # Custom legend title

# Annotate manually if t_test_result is significant
if (t_test_result$p.value < 0.05) {
  t_test_ph <- t_test_ph + annotate("text", x = 1.5, y = max(ph.data$pH), label = paste("p =", signif(t_test_result$p.value, 3)))
}

print(t_test_ph)
```



```{r}
# Group by Temp_Treatment and pH_Treatment to find summary stats and quantiles
summary_data <- mesocosm.data %>%
  group_by(Temp_Treatment, pH_Treatment) %>%
  dplyr::summarize(
    # Calculate mean and standard deviation for Temp_C
    Mean_Temp_C = mean(Temp_C, na.rm = TRUE),
    SD_Temp_C = sd(Temp_C, na.rm = TRUE) / sqrt(n()),
    
    # Calculate mean and standard deviation for DO_mgL
    Mean_DO_mgL = mean(DO_mgL, na.rm = TRUE),
    SD_DO_mgL = sd(DO_mgL, na.rm = TRUE) / sqrt(n()),
        
    # Calculate mean and standard deviation for DO_Percent
    Mean_DO_Percent = mean(DO_Percent, na.rm = TRUE),
    SD_DO_Percent = sd(DO_Percent, na.rm = TRUE) / sqrt(n()),
    
    # Calculate mean and standard deviation for Salinity
    Mean_Salinity = mean(Salinity, na.rm = TRUE),
    SD_Salinity = sd(Salinity, na.rm = TRUE) / sqrt(n()),
    
    # Calculate mean and standard deviation for Conductivity
    Mean_Conductivity = mean(Conductivity, na.rm = TRUE),
    SD_Conductivity = sd(Conductivity, na.rm = TRUE) / sqrt(n()),
    
    # Calculate mean and standard deviation for pH
    Mean_pH = mean_pH(pH, na.rm = TRUE),
    SD_pH = sd(pH, na.rm = TRUE) / sqrt(n()),
    
    # Calculate mean and standard deviation for TA
    Mean_TA = mean(TA, na.rm = TRUE),
    SD_TA = sd(TA, na.rm = TRUE) / sqrt(n()),
    
    # Calculate mean and standard deviation for pCO2
    Mean_pCO2 = mean(pCO2, na.rm = TRUE),
    SD_pCO2 = sd(pCO2, na.rm = TRUE) / sqrt(n()),
    
    # Calculate mean and standard deviation for HCO3
    Mean_HCO3 = mean(HCO3, na.rm = TRUE),
    SD_HCO3 = sd(HCO3, na.rm = TRUE) / sqrt(n()),
    
    # Calculate mean and standard deviation for CO3
    Mean_CO3 = mean(CO3, na.rm = TRUE),
    SD_CO3 = sd(CO3, na.rm = TRUE) / sqrt(n()),
    
    # Calculate mean and standard deviation for DIC
    Mean_DIC = mean(DIC, na.rm = TRUE),
    SD_DIC = sd(DIC, na.rm = TRUE) / sqrt(n())
    
) 

summary_table <- summary_data %>% 
  mutate(
    # Format columns as mean +- sd
    Mean_Temp_C = paste(round(Mean_Temp_C, 2), "±", round(SD_Temp_C, 2)),
    Mean_pH = paste(round(Mean_pH, 2), "±", round(SD_pH, 2)),
    Mean_Salinity = paste(round(Mean_Salinity, 2), "±", round(SD_Salinity, 2)),
    Mean_DO_Percent = paste(round(Mean_DO_Percent, 2), "±", round(SD_DO_Percent, 2)),
    Mean_Conductivity = paste(round(Mean_Conductivity, 2), "±", round(SD_Conductivity, 2)),
    Mean_TA = paste(round(Mean_TA, 2), "±", round(SD_TA, 2)),
    Mean_pCO2 = paste(round(Mean_pCO2, 2), "±", round(SD_pCO2, 2)),
    Mean_HCO3 = paste(round(Mean_HCO3, 2), "±", round(SD_HCO3, 2)),
    Mean_CO3 = paste(round(Mean_CO3, 2), "±", round(SD_CO3, 2)),
    Mean_DIC = paste(round(Mean_DIC, 2), "±", round(SD_DIC, 2))
  ) 

summary_table <- summary_table %>%
  select(-SD_Temp_C, -SD_pH, -SD_Salinity, -SD_DO_Percent, -SD_DO_mgL, -SD_Conductivity, -SD_TA, -SD_pCO2, -SD_HCO3, -SD_CO3, -SD_DIC) %>%
  arrange(pH_Treatment, Temp_Treatment)

# Rename columns to include units in labels
summary_table <- rename(summary_table,
  `Mean Temp (°C)` = Mean_Temp_C,
  `Mean pH` = Mean_pH,
  `Mean Salinity (ppt)` = Mean_Salinity,
  `Mean DO Percent (%)` = Mean_DO_Percent,
  `Mean DO (mg/L)` = Mean_DO_mgL,
  `Mean Conductivity (µS/cm)` = Mean_Conductivity,
  `Mean TA (µmol/kg)` = Mean_TA,
  `Mean pCO2 (atm)` = Mean_pCO2,
  `Mean DIC (µmol/kg)` = Mean_DIC,
  `Mean HCO3 (µmol/kg)` = Mean_HCO3,
  `Mean CO3 (µmol/kg)` = Mean_CO3
)

summary_table <- summary_table %>%
  mutate(
    pH_Treatment = factor(pH_Treatment, levels = c("Ambient", "Low", "Sump"))
  ) %>%
  arrange(pH_Treatment, Temp_Treatment)


#save summary table in csv format
write_csv(summary_data, here("Output", "mesocosm_summary_table.csv"))

#read csv file
read_csv(here("Output", "mesocosm_summary_table.csv")) 
  
  
  
```





# Plotting the Mesocosm Variables

```{r}

# Create a plot with standard error bars for Mean_DO_mgL
mesocosm_plot_do <- ggplot(summary_data, aes(x = factor(Temp_Treatment), y = Mean_DO_mgL, color = factor(pH_Treatment))) +
  geom_point(position = position_dodge(0.75), size = 2) +
  geom_errorbar(
    aes(ymin = Mean_DO_mgL - SD_DO_mgL, ymax = Mean_DO_mgL + SD_DO_mgL),
    width = 0.2,
    position = position_dodge(0.75),
    size = 1
  ) +
  labs(
    x = "Temp Treatment",
    y = "Mean DO (mg/L)",
    color = "pH Treatment"
  ) +
  ggtitle("Mean DO (mg/L) by pH Treatment (Mean DO +/- SE)") +
  scale_color_manual(values = c("Ambient" = "orange", "Low" = "cyan3")) +  # Specify colors as needed
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5, face = "bold"))  # Center and bold the title

# Create a plot with standard error bars for Mean_DO_Percent
mesocosm_plot_do_percent <- ggplot(summary_data, aes(x = factor(Temp_Treatment), y = Mean_DO_Percent, color = factor(pH_Treatment))) +
  geom_point(position = position_dodge(0.75), size = 2) +
  geom_errorbar(
    aes(ymin = Mean_DO_Percent - SD_DO_Percent, ymax = Mean_DO_Percent + SD_DO_Percent),
    width = 0.2,
    position = position_dodge(0.75),
    size = 1
  ) +
  labs(
    x = "Temp Treatment",
    y = "Mean DO %",
    color = "pH Treatment"
  ) +
  ggtitle("Mean DO % by pH Treatment (Mean DO +/- SE)") +
  scale_color_manual(values = c("Ambient" = "orange", "Low" = "cyan3")) +  # Specify colors as needed
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5, face = "bold"))  # Center and bold the title

# Create a plot with standard error bars for Mean_Salinity
mesocosm_plot_salinity <- ggplot(summary_data, aes(x = factor(Temp_Treatment), y = Mean_Salinity, color = factor(pH_Treatment))) +
  geom_point(position = position_dodge(0.75), size = 2) +
  geom_errorbar(
    aes(ymin = Mean_Salinity - SD_Salinity, ymax = Mean_Salinity + SD_Salinity),
    width = 0.2,
    position = position_dodge(0.75),
    size = 1
  ) +
  labs(
    x = "Temp Treatment",
    y = "Mean Salinity",
    color = "pH Treatment"
  ) +
  ggtitle("Mean Salinity by pH Treatment (Mean Salinity +/- SE)") +
  scale_color_manual(values = c("Ambient" = "orange", "Low" = "cyan3")) +  # Specify colors as needed
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5, face = "bold"))  # Center and bold the title

# Create a plot with standard error bars for Mean_Conductivity
mesocosm_plot_conductivity <- ggplot(summary_data, aes(x = factor(Temp_Treatment), y = Mean_Conductivity, color = factor(pH_Treatment))) +
  geom_point(position = position_dodge(0.75), size = 2) +
  geom_errorbar(
    aes(ymin = Mean_Conductivity - SD_Conductivity, ymax = Mean_Conductivity + SD_Conductivity),
    width = 0.2,
    position = position_dodge(0.75),
    size = 1
  ) +
  labs(
    x = "Temp Treatment",
    y = "Mean Conductivity",
    color = "pH Treatment"
  ) +
  ggtitle("Mean Conductivity by pH Treatment (Mean Conductivity +/- SE)") +
  scale_color_manual(values = c("Ambient" = "orange", "Low" = "cyan3")) +  # Specify colors as needed
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5, face = "bold"))  # Center and bold the title


# Create a plot with standard error bars for Mean_Temp_C
mesocosm_plot_temp <- ggplot(summary_data, aes(x = factor(Temp_Treatment), y = Mean_Temp_C, color = factor(pH_Treatment))) +
  geom_point(position = position_dodge(0.75), size = 2) +
  geom_errorbar(
    aes(ymin = Mean_Temp_C - SD_Temp_C, ymax = Mean_Temp_C + SD_Temp_C),
    width = 0.2,
    position = position_dodge(0.75),
    size = 1
  ) +
  geom_hline(yintercept = c(12, 14, 16, 18, 20, 22, 24, 26), linetype = "dashed") +
  labs(
    x = "Temp Treatment",
    y = "Mean Temp (°C)",
    color = "pH Treatment"
  ) +
  ggtitle("Mean Temperature by pH Treatment (Mean Temp +/- SE)") +
  scale_color_manual(values = c("Ambient" = "orange", "Low" = "cyan3")) +  # Specify orange and cyan as colors
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5, face = "bold"))  # Center and bold the title


# Create a plot with standard error bars for Mean_pH
mesocosm_plot_pH <- ggplot(summary_data, aes(x = factor(Temp_Treatment), y = Mean_pH, color = factor(pH_Treatment))) +
  geom_point(position = position_dodge(0.75), size = 2) +
  geom_errorbar(
    aes(ymin = Mean_pH - SD_pH, ymax = Mean_pH + SD_pH),
    width = 0.2,
    position = position_dodge(0.75),
    size = 1
  ) +
  geom_hline(yintercept = c(7.7, 8.0), linetype = "dashed", color = c("cyan3", "orange")) +
  labs(
    x = "Temp Treatment",
    y = "Mean pH",
    color = "pH Treatment"
  ) +
  ggtitle("Mean pH by Treatment (Mean pH +/- SE)") +
  scale_color_manual(values = c("Ambient" = "orange", "Low" = "cyan3", "Sump"="grey")) +  # Specify colors as needed
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5, face = "bold"))  # Center and bold the title

# Create a point plot with error bars for Mean pH and SE, colored in orange and cyan3
mesocosm_mean_pH_plot <- ggplot(summary_data, aes(x = pH_Treatment, y = Mean_pH, color = pH_Treatment)) +
  geom_point(position = position_dodge(width = 0.2), size = 3) +
  geom_errorbar(aes(ymin = Mean_pH - SD_pH, ymax = Mean_pH + SD_pH, color = pH_Treatment), position = position_dodge(width = 0.2), width = 0.2) +
  labs(title = "pH Treatment Summary (Mean pH +/- SE)",
       x = "pH Treatment",
       y = "Mean pH",
       color = "pH Treatment") +
  theme_minimal() +
  scale_color_manual(values = c("orange", "cyan3", "grey")) +
  theme(plot.title = element_text(hjust = 0.5, face = "bold"))  # Center and bold the title

# Display the plots
print(mesocosm_plot_do)
print(mesocosm_plot_do_percent)
print(mesocosm_plot_conductivity)
print(mesocosm_plot_salinity)
print(mesocosm_plot_temp)
print(mesocosm_plot_pH)
print(mesocosm_mean_pH_plot)

# Saving Plots to Output Folder 

ggsave(here("Output/mesocosm_plot_do.png"), mesocosm_plot_do, width = 8, height = 6)
ggsave(here("Output/mesocosm_plot_do_percent.png"), mesocosm_plot_do_percent, width = 8, height = 6)
ggsave(here("Output/mesocosm_plot_conductivity.png"), mesocosm_plot_conductivity, width = 8, height = 6)
ggsave(here("Output/mesocosm_plot_salinity.png"), mesocosm_plot_salinity, width = 8, height = 6)
ggsave(here("Output/mesocosm_plot_temp.png"), mesocosm_plot_temp, width = 8, height = 6)
ggsave(here("Output/mesocosm_plot_pH.png"), mesocosm_plot_pH, width = 8, height = 6)
ggsave(here("Output/mesocosm_mean_pH_plot.png"), mesocosm_mean_pH_plot, width = 8, height = 6)

```

```{r}

pH_Temp_data <- summary_data %>%
  filter(pH_Treatment != "Sump") %>% 
  select(pH_Treatment, Temp_Treatment, Mean_Temp_C, SD_Temp_C, Mean_pH, SD_pH) %>%
  na.omit()

# Calculate the overall mean pH
low_mean_pH <- mesocosm.data %>% 
  filter(pH_Treatment == "Low") %>%
  dplyr::summarize(Mean_pH = mean_pH(pH, na.rm = TRUE),
                   SD_pH = sd(pH, na.rm = TRUE),
                   N = n(),
                   SE = SD_pH / sqrt(N),
                   Upper_CI = Mean_pH + 1.96 * SE,
                   Lower_CI = Mean_pH - 1.96 * SE)

# Calculate the overall mean pH
ambient_mean_pH <- mesocosm.data %>% 
  filter(pH_Treatment == "Ambient") %>%
  dplyr::summarize(Mean_pH = mean(pH, na.rm = TRUE),
                   SD_pH = sd(pH, na.rm = TRUE),
                   N = n(),
                   SE = SD_pH / sqrt(N),
                   Upper_CI = Mean_pH + 1.96 * SE,
                   Lower_CI = Mean_pH - 1.96 * SE)

# Create a new variable for dodging manually
pH_Temp_data$Temp_Treatment_Offset <- as.numeric(pH_Temp_data$Temp_Treatment)
# Apply a different offset for each pH_Treatment
pH_Temp_data$Temp_Treatment_Offset <- ifelse(pH_Temp_data$pH_Treatment == "Low",
                                              pH_Temp_data$Temp_Treatment_Offset - 0.2,
                                              pH_Temp_data$Temp_Treatment_Offset + 0.2)


# First, create a data frame with the y-intercepts and corresponding colors
hline_data <- data.frame(
  yintercept = seq(12, 26, by = 2),
  Temp_Treatment = seq(12, 26, by = 2)  # This should match your Temp_Treatment variable
)

# Then map the colors to this new data within geom_hline()
mesocosm_plot_temp_pub <- ggplot(pH_Temp_data, aes(x = Temp_Treatment_Offset, y = Mean_Temp_C)) +
  geom_point(aes(color = as.numeric(Temp_Treatment)), size = 2) +
  geom_errorbar(
    aes(ymin = Mean_Temp_C - SD_Temp_C, ymax = Mean_Temp_C + SD_Temp_C, color = as.numeric(Temp_Treatment)),
    width = 0.1,
    size = 0.75
  ) +
  scale_color_gradient(low = "#FFEC8B", high = "#CD3333", name = "Temp (°C)", limits = c(12, 26), breaks = seq(12, 26, by = 2)) +
  scale_x_continuous(breaks = seq(12, 26, by = 2), limits = c(11, 27)) +
  scale_y_continuous(breaks = seq(12, 26, by = 2), limits = c(11, 27)) +
  geom_hline(data = hline_data, aes(yintercept = yintercept, color = as.numeric(Temp_Treatment)), linetype = "dashed") +
  labs(x = "Temp Treatment", y = "Mean Temp (°C)", color = "Temp (°C)") +
  theme_classic() +
  theme(
    text = element_text(family = "Times New Roman", size = 12),
    axis.title = element_text(size = 12),
    legend.position = "right"
  )


# Create a plot with standard error bars for Mean_pH
mesocosm_plot_pH_pub <- ggplot(pH_Temp_data, aes(x = factor(Temp_Treatment), y = Mean_pH, color = factor(pH_Treatment))) +
  geom_point(position = position_dodge(0.75), size = 2) +
  geom_errorbar(
    aes(ymin = Mean_pH - SD_pH, ymax = Mean_pH + SD_pH),
    width = 0.2,
    position = position_dodge(0.75),
    size = 1
  ) +
  geom_hline(aes(yintercept = ambient_mean_pH$Mean_pH), linetype = "dashed", color = c("darkcyan")) +
  geom_hline(aes(yintercept = low_mean_pH$Mean_pH), linetype = "dashed", color = c("cyan3")) +
  # Add shaded confidence intervals for the overall means
  #geom_ribbon(data = mean_pH_data, aes(ymin = Lower_CI, ymax = Upper_CI), alpha = 0.25) +
  labs(x = "Temp Treatment",
    y = "Mean pH",
    color = "pH Treatment"
  ) +
  scale_color_manual(values = c("Ambient" = "darkcyan", "Low" = "cyan3")) +  # Specify colors as needed
  theme_classic() +
  theme(text = element_text(family = "Times New Roman", size = 12),
        axis.title = element_text(size = 12),
        legend.position = "right") 



# Create a point plot with error bars for Mean pH and SE, colored in orange and cyan3
mesocosm_mean_pH_plot_pub <- ggplot(pH_Temp_data, aes(x = pH_Treatment, y = Mean_pH, color = pH_Treatment)) +
  geom_hline(aes(yintercept = ambient_mean_pH$Mean_pH), linetype = "dashed", color = c("darkcyan")) +
  geom_hline(aes(yintercept = low_mean_pH$Mean_pH), linetype = "dashed", color = c("cyan3")) +
  geom_point(position = position_dodge(width = 0.2), size = 3) +
  geom_errorbar(aes(ymin = Mean_pH - SD_pH, ymax = Mean_pH + SD_pH, color = pH_Treatment), position = position_dodge(width = 0.2), width = 0.2) +
  labs(x = "pH Treatment",
       y = "Mean pH",
       color = "pH Treatment") +
  theme_classic() +
  scale_color_manual(values = c("darkcyan", "cyan3")) +
  theme(text = element_text(family = "Times New Roman", size = 12),
        axis.title = element_text(size = 12),
        legend.position = "right")  # Center and bold the title

# Display the plots
print(mesocosm_plot_temp_pub)
print(mesocosm_plot_pH_pub)
print(mesocosm_mean_pH_plot_pub)

```

```{r}


# Filter out rows where pH_Treatment is not equal to "Sump"
temp_summary_data <- summary_data %>%
  filter(pH_Treatment != "Sump") %>% 
  select(Mean_Temp_C, Temp_Treatment, pH_Treatment)

temp_summary_data$Temp_Treatment <- as.factor(temp_summary_data$Temp_Treatment)
temp_summary_data$pH_Treatment <- as.factor(temp_summary_data$pH_Treatment)
# Perform ANOVA
anova_result <- aov(Mean_Temp_C ~ Temp_Treatment * pH_Treatment, data = temp_summary_data)

# Conduct Tukey's HSD test
tukey_result <- TukeyHSD(anova_result)

# Print ANOVA table
print(anova_result)

# Print Tukey's HSD test results
print(tukey_result)

# Filter out rows where pH_Treatment is not equal to "Sump"
pH_summary_data <- summary_data %>%
  filter(pH_Treatment != "Sump") %>% 
  select(Mean_pH=Mean_pH, Temp_Treatment, pH_Treatment)

pH_summary_data$Temp_Treatment <- as.factor(pH_summary_data$Temp_Treatment)
pH_summary_data$pH_Treatment <- as.factor(pH_summary_data$pH_Treatment)
# Perform ANOVA
anova_result <- aov(Mean_pH ~ Temp_Treatment * pH_Treatment, data = pH_summary_data)

# Conduct Tukey's HSD test
tukey_result <- TukeyHSD(anova_result)

# Print ANOVA table
print(anova_result)

# Print Tukey's HSD test results
print(tukey_result)
```


### Mesocosm Logger Time Series Data ###


```{r}
#Reading in CSV
mesocosm.metadata <- read_csv(here("Data", "Mesocosm_Data", "Mesocosm_Metadata.csv"))

#Reading in CSV
TNK_2 <- read_csv(
  here::here("Data", "Mesocosm_Data", "Mesocosm_HOBO_Temperature", "TNK-2-SN20565253 2022-09-03 20_17_13 -0700.csv"),
  skip = 2,
  col_names = c("Datetime", "Temp_C", "Host Connect", "Button Down", "Button Up", "EOF")
) %>%
  select(1:2)%>%
  slice(-1) %>% 
  mutate(Datetime = ymd_hms(Datetime),
         Time = hms(format(Datetime, format = "%H:%M:%S")),
         Temp_C= as.numeric(Temp_C),
         Tank_ID = "TNK_2")

TNK_3 <- read_csv(
  here::here("Data", "Mesocosm_Data", "Mesocosm_HOBO_Temperature", "TNK-3-SN20565265 2022-09-03 20_18_14 -0700.csv"),
  skip = 2,
  col_names = c("Datetime", "Temp_C", "Host Connect", "Button Down", "Button Up", "EOF")
) %>%
  select(1:2)%>%
  slice(-1) %>% 
  mutate(Datetime = ymd_hms(Datetime),
         Time = hms(format(Datetime, format = "%H:%M:%S")),
         Temp_C= as.numeric(Temp_C),
         Tank_ID = "TNK_3")

TNK_4 <- read_csv(
  here::here("Data", "Mesocosm_Data", "Mesocosm_HOBO_Temperature", "TNK-4-SN20565252 2022-09-03 20_19_11 -0700.csv"),
  skip = 2,
  col_names = c("Datetime", "Temp_C", "Host Connect", "Button Down", "Button Up", "EOF")
) %>%
  select(1:2)%>%
  slice(-1) %>% 
  mutate(Datetime = ymd_hms(Datetime),
         Time = hms(format(Datetime, format = "%H:%M:%S")),
         Temp_C= as.numeric(Temp_C),
         Tank_ID = "TNK_4")

TNK_5 <- read_csv(
  here::here("Data", "Mesocosm_Data", "Mesocosm_HOBO_Temperature", "TNK-5-SN20569922 2022-09-03 20_20_18 -0700.csv"),
  skip = 2,
  col_names = c("Datetime", "Temp_C", "Host Connect", "Button Down", "Button Up", "EOF")
) %>%
  select(1:2)%>%
  slice(-1) %>% 
  mutate(Datetime = ymd_hms(Datetime),
         Time = hms(format(Datetime, format = "%H:%M:%S")),
         Temp_C= as.numeric(Temp_C),
         Tank_ID = "TNK_5")

TNK_6 <- read_csv(
  here::here("Data", "Mesocosm_Data", "Mesocosm_HOBO_Temperature", "TNK-6-SN20565263 2022-09-03 20_21_26 -0700.csv"),
  skip = 2,
  col_names = c("Datetime", "Temp_C", "Host Connect", "Button Down", "Button Up", "EOF")
) %>%
  select(1:2)%>%
  slice(-1) %>% 
  mutate(Datetime = ymd_hms(Datetime),
         Time = hms(format(Datetime, format = "%H:%M:%S")),
         Temp_C= as.numeric(Temp_C),
         Tank_ID = "TNK_6")

TNK_7 <- read_csv(
  here::here("Data", "Mesocosm_Data", "Mesocosm_HOBO_Temperature", "TNK-7-SN20714140 2022-09-03 20_23_13 -0700.csv"),
  skip = 2,
  col_names = c("Datetime", "Temp_C", "Host Connect", "Button Down", "Button Up", "EOF")
) %>%
  select(1:2)%>%
  slice(-1) %>% 
  mutate(Datetime = ymd_hms(Datetime),
         Time = hms(format(Datetime, format = "%H:%M:%S")),
         Temp_C= as.numeric(Temp_C),
         Tank_ID = "TNK_7")

TNK_8 <- read_csv(
  here::here("Data", "Mesocosm_Data", "Mesocosm_HOBO_Temperature", "TNK-8-SN20565261 2022-09-03 20_24_16 -0700.csv"),
  skip = 2,
  col_names = c("Datetime", "Temp_C", "Host Connect", "Button Down", "Button Up", "EOF")
) %>%
  select(1:2)%>%
  slice(-1) %>% 
  mutate(Datetime = ymd_hms(Datetime),
         Time = hms(format(Datetime, format = "%H:%M:%S")),
         Temp_C= as.numeric(Temp_C),
         Tank_ID = "TNK_8")

TNK_9 <- read_csv(
  here::here("Data", "Mesocosm_Data", "Mesocosm_HOBO_Temperature", "TNK-9-SN20565255 2022-09-03 20_25_16 -0700.csv"),
  skip = 2,
  col_names = c("Datetime", "Temp_C", "Host Connect", "Button Down", "Button Up", "EOF")
) %>%
  select(1:2)%>%
  slice(-1) %>% 
  mutate(Datetime = ymd_hms(Datetime),
         Time = hms(format(Datetime, format = "%H:%M:%S")),
         Temp_C= as.numeric(Temp_C),
         Tank_ID = "TNK_9")

TNK_10 <- read_csv(
  here::here("Data", "Mesocosm_Data", "Mesocosm_HOBO_Temperature", "TNK-10-SN20714141 2022-09-03 20_26_26 -0700.csv"),
  skip = 2,
  col_names = c("Datetime", "Temp_C", "Host Connect", "Button Down", "Button Up", "EOF")
) %>%
  select(1:2)%>%
  slice(-1) %>% 
  mutate(Datetime = ymd_hms(Datetime),
         Time = hms(format(Datetime, format = "%H:%M:%S")),
         Temp_C= as.numeric(Temp_C),
         Tank_ID = "TNK_10")

TNK_11 <- read_csv(
  here::here("Data", "Mesocosm_Data", "Mesocosm_HOBO_Temperature", "TNK-11-SN20565260 2022-09-03 20_27_21 -0700.csv"),
  skip = 2,
  col_names = c("Datetime", "Temp_C", "Host Connect", "Button Down", "Button Up", "EOF")
) %>%
  select(1:2)%>%
  slice(-1) %>% 
  mutate(Datetime = ymd_hms(Datetime),
         Time = hms(format(Datetime, format = "%H:%M:%S")),
         Temp_C= as.numeric(Temp_C),
         Tank_ID = "TNK_11")

TNK_12 <- read_csv(
  here::here("Data", "Mesocosm_Data", "Mesocosm_HOBO_Temperature", "TNK-12-SN20565262 2022-09-03 20_29_03 -0700.csv"),
  skip = 2,
  col_names = c("Datetime", "Temp_C", "Host Connect", "Button Down", "Button Up", "EOF")
) %>%
  select(1:2)%>%
  slice(-1) %>% 
  mutate(Datetime = ymd_hms(Datetime),
         Time = hms(format(Datetime, format = "%H:%M:%S")),
         Temp_C= as.numeric(Temp_C),
         Tank_ID = "TNK_12")

TNK_13 <- read_csv(
  here::here("Data", "Mesocosm_Data", "Mesocosm_HOBO_Temperature", "TNK-13-SN20714139 2022-09-03 20_30_01 -0700.csv"),
  skip = 2,
  col_names = c("Datetime", "Temp_C", "Host Connect", "Button Down", "Button Up", "EOF")
) %>%
  select(1:2)%>%
  slice(-1) %>% 
  mutate(Datetime = ymd_hms(Datetime),
         Time = hms(format(Datetime, format = "%H:%M:%S")),
         Temp_C= as.numeric(Temp_C),
         Tank_ID = "TNK_13")

TNK_14 <- read_csv(
  here::here("Data", "Mesocosm_Data", "Mesocosm_HOBO_Temperature", "TNK-14-SN20565254 2022-09-03 20_31_00 -0700.csv"),
  skip = 2,
  col_names = c("Datetime", "Temp_C", "Host Connect", "Button Down", "Button Up", "EOF")
) %>%
  select(1:2)%>%
  slice(-1) %>% 
  mutate(Datetime = ymd_hms(Datetime),
         Time = hms(format(Datetime, format = "%H:%M:%S")),
         Temp_C= as.numeric(Temp_C),
         Tank_ID = "TNK_14")

TNK_15 <- read_csv(
  here::here("Data", "Mesocosm_Data", "Mesocosm_HOBO_Temperature", "TNK-15-SN20565250 2022-09-03 20_16_18 -0700.csv"),
  skip = 2,
  col_names = c("Datetime", "Temp_C", "Host Connect", "Button Down", "Button Up", "EOF")
) %>%
  select(1:2)%>%
  slice(-1) %>% 
  mutate(Datetime = ymd_hms(Datetime),
         Time = hms(format(Datetime, format = "%H:%M:%S")),
         Temp_C= as.numeric(Temp_C),
         Tank_ID = "TNK_15")

TNK_16 <- read_csv(
  here::here("Data", "Mesocosm_Data", "Mesocosm_HOBO_Temperature", "TNK-16-SN20569983 2022-09-03 20_32_03 -0700.csv"),
  skip = 2,
  col_names = c("Datetime", "Temp_C", "Host Connect", "Button Down", "Button Up", "EOF")
) %>%
  select(1:2)%>%
  slice(-1) %>% 
  mutate(Datetime = ymd_hms(Datetime),
         Time = hms(format(Datetime, format = "%H:%M:%S")),
         Temp_C= as.numeric(Temp_C),
         Tank_ID = "TNK_16")

TNK_18 <- read_csv(
  here::here("Data", "Mesocosm_Data", "Mesocosm_HOBO_Temperature", "TNK-18-SN20569985 2022-09-03 20_35_53 -0700.csv"),
  skip = 2,
  col_names = c("Datetime", "Temp_C", "Host Connect", "Button Down", "Button Up", "EOF")
) %>%
  select(1:2)%>%
  slice(-1) %>% 
  mutate(Datetime = ymd_hms(Datetime),
         Time = hms(format(Datetime, format = "%H:%M:%S")),
         Temp_C= as.numeric(Temp_C),
         Tank_ID = "TNK_18")

TNK_AIR <- read_csv(
  here::here("Data", "Mesocosm_Data", "Mesocosm_HOBO_Temperature", "TNK-AIR-SN20565251 2022-09-03 20_14_50 -0700.csv"),
  skip = 2,
  col_names = c("Datetime", "Temp_C", "Host Connect", "Button Down", "Button Up", "EOF")
) %>%
  select(1:2)%>%
  slice(-1) %>% 
  mutate(Datetime = ymd_hms(Datetime),
         Time = hms(format(Datetime, format = "%H:%M:%S")),
         Temp_C= as.numeric(Temp_C),
         Tank_ID = "TNK_AIR")

TNK_SMP <- read_csv(
  here::here("Data", "Mesocosm_Data", "Mesocosm_HOBO_Temperature", "TNK-SMP-SN20569984 2022-09-03 20_33_58 -0700.csv"),
  skip = 2,
  col_names = c("Datetime", "Temp_C", "Host Connect", "Button Down", "Button Up", "EOF")
) %>%
  select(1:2)%>%
  slice(-1) %>% 
  mutate(Datetime = ymd_hms(Datetime),
         Time = hms(format(Datetime, format = "%H:%M:%S")),
         Temp_C= as.numeric(Temp_C),
         Tank_ID = "TNK_SMP")


```


```{r}
tank_timeseries <- bind_rows(TNK_2, TNK_3, TNK_4, TNK_5, TNK_6, TNK_7, TNK_8, TNK_9, TNK_10, TNK_11, TNK_12, TNK_13, TNK_14, TNK_15, TNK_16, TNK_18, TNK_AIR, TNK_SMP)

filtered_timeseries <- tank_timeseries %>%
  group_by(Tank_ID) %>%
  filter(Datetime >= "2022-08-23", #day experiment began - not counting acclimation period
         Datetime <= "2022-09-01") %>% 
mutate(
    Tide = case_when(
      Time > hms("13:00:00") & Time < hms("17:00:00") ~ "Low",
      Time > hms("01:00:00") & Time < hms("05:00:00") ~ "Low",
      Time > hms("19:00:00") & Time < hms("23:00:00") ~ "High",
      Time > hms("07:00:00") & Time < hms("11:00:00") ~ "High",
      TRUE ~ "Intermediate"  # Add an intermediate tide for transitional periods
    )
  ) %>%
  na.omit() %>%
  left_join(mesocosm.metadata)

mesocosm.data <- read_csv(here::here("Data", "Mesocosm_Data", "Completed_Mesocosm_Dataset_Carbonate.csv"))

#spot check times and values
mesocosm.data<- mesocosm.data %>%
  mutate(Datetime = ifelse(pH_Treatment == "Low", 
                      ymd_hms(paste0(Date, " 10:00:00"), tz = "UTC"), 
                      ymd_hms(paste0(Date, " 11:00:00"), tz = "UTC")),
    Datetime = as.POSIXct(Datetime)) %>%
  select(Datetime, Tank_ID, Temp_C_Spot=Temp_C) %>%
  na.omit()

# join the time series and the spot check data 
filtered_timeseries <- filtered_timeseries %>%
  left_join(mesocosm.data, by = c("Datetime", "Tank_ID")) %>% 
  mutate(Date = as.Date(Datetime)) %>% 
  filter(Datetime >= "2022-08-23", #day experiment began - not counting acclimation period
         Datetime <= "2022-09-01")

difference <- filtered_timeseries %>%
  filter(!is.na(Temp_C_Spot)) %>%
  group_by(Tank_ID, Date) %>%
  dplyr::summarize(Temp_Diff = mean(Temp_C - Temp_C_Spot, na.rm = TRUE))

# 2. Apply the difference to correct the values in the time series data
tank_timeseries_corrected <- filtered_timeseries %>%
  left_join(difference, by = c("Tank_ID", "Date")) %>%
  mutate(Temp_C_Corrected = Temp_C - Temp_Diff)

# 3. Create a plot of the corrected temperature values
logger.temp.plot <- ggplot(tank_timeseries_corrected, aes(x = Datetime, y = Temp_C_Corrected)) +
  geom_point(aes(color = Tide), na.rm = TRUE) +
  geom_hline(aes(yintercept = Temp_Treatment)) +
  facet_wrap(~Tank_ID) +
  scale_color_discrete(name = "Tank") +
  scale_y_continuous(breaks = seq(12, 36, by = 4)) +
  labs(
    title = "Mesocosm Temperature Range",
    x = "Date",
    y = "Temperature (°C)"
  ) +
  theme_minimal() +
  theme(
    text = element_text(family = "Helvetica", size = 5, color = "black"),
    legend.title = element_text(size = 5),
    plot.title = element_text(face = "bold", hjust = 0.5)  # Bold and centered title
  )
logger.temp.plot

logger.hightide.temp <- tank_timeseries_corrected %>% 
  filter(Tide == "High") %>%
    filter(Date != "2022-08-29",
           Date != "2022-08-27") #water spillage dates (increase in watertemp not experienced)

logger.lowtide.temp.plot <- ggplot(logger.hightide.temp, aes(x = Datetime, y = Temp_C_Corrected)) +
  geom_point() +
  geom_hline(aes(yintercept = Temp_Treatment)) +
  facet_wrap(~Tank_ID) +
  scale_color_discrete(name = "Tank") +
  scale_y_continuous(breaks = seq(12, 36, by = 4)) +
  labs(
    title = "Mesocosm Temperature Range",
    x = "Date",
    y = "Temperature (°C)"
  ) +
  theme_minimal() +
  theme(
    text = element_text(family = "Helvetica", size = 5, color = "black"),
    legend.title = element_text(size = 5),
    plot.title = element_text(face = "bold", hjust = 0.5)  # Bold and centered title
  )

logger.lowtide.temp.plot 

tank_timeseries_corrected <- logger.hightide.temp

# 1. Calculate the mean for each combination of Tank_Treatment and pH_Treatment
means <- tank_timeseries_corrected %>%
  filter(pH_Treatment != "Sump", pH_Treatment != "Air") %>% 
  group_by(Temp_Treatment, pH_Treatment) %>%
  dplyr::summarize(Mean_Temp_C = mean(Temp_C_Corrected, na.rm = TRUE),
                   SD_Temp_C = sd(Temp_C_Corrected, na.rm = TRUE))

# 2. Compute the IQR for each combination
iqr_values <- tank_timeseries_corrected %>%
  group_by(Temp_Treatment, pH_Treatment) %>%
  dplyr::summarize(Q1 = quantile(Temp_C_Corrected, 0.25, na.rm = TRUE),
            Q3 = quantile(Temp_C_Corrected, 0.75, na.rm = TRUE),
            IQR = Q3 - Q1)

# 3. Filter out values that fall outside a certain range defined by the IQR
filtered_data <- tank_timeseries_corrected %>%
  left_join(iqr_values, by = c("Temp_Treatment", "pH_Treatment")) %>%
  filter(Temp_C_Corrected >= Q1 - 1.5 * IQR, Temp_C_Corrected <= Q3 + 1.5 * IQR)

filtered_means <- filtered_data %>%
  filter(pH_Treatment != "Sump", pH_Treatment != "Air") %>%
  filter(Tide == "High") %>%
  group_by(Temp_Treatment, pH_Treatment) %>%
  dplyr::summarize(Mean_Temp_C = mean(Temp_C_Corrected, na.rm = TRUE))

write_csv(filtered_means, here::here("Data", "Mesocosm_Data", "Mesocosm_Temp_Filtered_Means.csv"))
write_csv(means, here::here("Data", "Mesocosm_Data", "Mesocosm_Temp_Means.csv"))

print(filtered_means)
print(means)
 
means <- means %>% 
  mutate(Temp_Treatment= case_when(
    pH_Treatment == "Low" ~ Temp_Treatment - 0.2,
    pH_Treatment == "Ambient" ~ Temp_Treatment + 0.2
  ))

# First, create a data frame with the y-intercepts and corresponding colors
hline_data <- data.frame(
  yintercept = seq(12, 26, by = 2),
  Temp_Treatment = seq(12, 26, by = 2)  # This should match your Temp_Treatment variable
)

# Then map the colors to this new data within geom_hline()
mesocosm_plot_temp_pub <- ggplot(means, aes(x = Temp_Treatment, y = Mean_Temp_C)) +
  geom_point(aes(color = as.numeric(Temp_Treatment)), size = 2) +
  geom_errorbar(
    aes(ymin = Mean_Temp_C - SD_Temp_C, ymax = Mean_Temp_C + SD_Temp_C, color = as.numeric(Temp_Treatment)),
    width = 0.1,
    size = 0.75
  ) +
  scale_color_gradient(low = "#FFEC8B", high = "#CD3333", name = "Temp (°C)", limits = c(10, 30), breaks = seq(10, 30, by = 4)) +
  scale_x_continuous(breaks = seq(12, 26, by = 2), limits = c(10, 28)) +
  scale_y_continuous(breaks = seq(12, 26, by = 2), limits = c(10, 29)) +
  geom_hline(data = hline_data, aes(yintercept = yintercept, color = as.numeric(Temp_Treatment)), linetype = "dashed") +
  labs(x = "Temperature Treatment", y = "Mean Temp (°C)", color = "Temp (°C)") +
  theme_classic() +
  theme(
    text = element_text(family = "Times New Roman", size = 12),
    axis.title = element_text(size = 12),
    legend.position = "right"
  )

plot(mesocosm_plot_temp_pub)

```

```{r}

# Reading in mesocosm treatment metadata
mesocosm.metadata <- read_csv(here("Data", "Mesocosm_Data", "Mesocosm_Metadata.csv"))

# Selecting all files from the folders
files <- list.files(here("Data", "Mesocosm_Data", "Mesocosm_HOBO_Temperature"),
                    pattern = ".csv", full.names = TRUE) %>% 
  sort(decreasing = TRUE) # Files ordered by decreasing values

# Reading in temperature data
temp.data <- files %>%  # Read CSV files into one data frame
  set_names(files) %>%  # Set names of columns based on file names
  map_dfr(~ read_csv(.x, skip = 4, col_names = c("Date", "Temp"), col_types = list(col_character(), col_double())), .id = "filename") %>% # Skip metadata
  mutate(
    Tank_ID = str_extract(filename, pattern = regex("TNK-[0-9]+|TNK-[A-Z]{3}")), # String extract 
    Tank_ID = str_replace(Tank_ID, pattern = "-", replacement = "_"), # Replace pattern 
    Date = ymd_hms(Date), # Change to date format
    Time = hms(format(Date, format = "%H:%M:%S")) # Separate date and time columns 
  ) %>%  
  select(Tank_ID, Date, Time, Temp) # Selecting columns

#cleaning and filtering data
temp.clean <- temp.data %>% 
  mutate(Tide = ifelse(Time > hms("12:00:00") & Time < hms("18:00:00") | 
                       Time > hms("00:00:00") & Time < hms("06:00:00"),
                       "Low","High")) %>% # tide columns
  filter(Date >= "2022-08-16",
         Date <= "2022-09-02") %>% #filtering for length of the experiment
  group_by(Tank_ID) %>% #group by Tank_ID
  na.omit() %>% 
  left_join(mesocosm.metadata)

logger.temp.plot <- ggplot(temp.clean, aes(x = Date, y = Temp)) +
  geom_point(aes(color = Tide), na.rm = TRUE) +
  geom_hline(aes(yintercept = Temp_Treatment)) +
  facet_wrap(~Tank_ID) +
  scale_color_discrete(name = "Tank") +
  scale_y_continuous(breaks = seq(12, 36, by = 4)) +
  labs(
    title = "Mesocosm Temperature Range",
    x = "Date",
    y = "Temperature (°C)"
  ) +
  theme_minimal() +
  theme(
    text = element_text(family = "Helvetica", size = 10, color = "black"),
    legend.title = element_text(size = 10),
    plot.title = element_text(face = "bold", hjust = 0.5)  # Bold and centered title
  )

# Filter for air temperature
air.temperature <- temp.clean %>%
  filter(Time > hms("13:30:00") & Time < hms("16:30:00") |
         Time > hms("01:30:00") & Time < hms("04:30:00"))

# Filter for water temperature
water.temperature <- temp.clean %>%
  filter(Time > hms("07:30:00") & Time < hms("11:30:00") |
         Time > hms("19:30:00") & Time < hms("23:30:00"))

# Create the air temperature plot
air.temp.plot <- ggplot(air.temperature, aes(x = Date, y = Temp, color = Tide)) +
  geom_point() +
  facet_wrap(~Tank_ID) +
  theme_minimal() +
  theme(
    text = element_text(family = "Helvetica", size = 10, color = 'black'),
    legend.title = element_text(size = 12),
    plot.title = element_text(face = "bold", hjust = 0.5)  # Bold and centered title
  ) +
  scale_color_discrete(name = "Tide") +
  scale_y_continuous(breaks = seq(12, 36, by = 4)) +
  labs(title = "Air Temperature Range") +
  xlab("Date") +
  ylab("Temperature (°C)")

# Create the water temperature plot
water.temp.plot <- ggplot(water.temperature, aes(x = Date, y = Temp, color = Tide)) +
  geom_point() +
  facet_wrap(~Tank_ID) +
  theme_minimal() +
  theme(
    text = element_text(family = "Helvetica", size = 10, color = 'black'),
    legend.title = element_text(size = 12),
    plot.title = element_text(face = "bold", hjust = 0.5)  # Bold and centered title
  ) +
  scale_color_discrete(name = "Tide") +
  scale_y_continuous(breaks = seq(12, 36, by = 4)) +
  labs(title = "Water Temperature Range") +
  xlab("Date") +
  ylab("Temperature (°C)")

#Display plots
print(logger.temp.plot)
print(air.temp.plot)
print(water.temp.plot)

# Save Mesocosm HOBO logger Plots
ggsave(here("Output/logger_temp_plot.png"), logger.temp.plot, width = 8, height = 6)
ggsave(here("Output/air_temp_plot.png"), air.temp.plot, width = 8, height = 6)
ggsave(here("Output/water_temp_plot.png"), water.temp.plot, width = 8, height = 6)



```

# Mesocosm High Tide Temperatures

```{r}

# Filtering out High Tide Temperatures
high.tide.temperatures <- water.temperature %>%
  filter(Tide == 'High' & !Tank_ID %in% c("TNK_SMP", "TNK_AIR")) %>% 
  filter(Date >= "2022-08-16",
         Date <= "2022-09-02")

# Calculate the mean and standard error
high.tide.temperatures_summary <- high.tide.temperatures %>%
  group_by(Tank_ID, Temp_Treatment, pH_Treatment) %>%
  summarise(
    Mean_Temp = mean(Temp),
    SD_Temp = sd(Temp) / sqrt(n())
  ) %>%
  ungroup()


# Create the box and whisker plot
ggplot(high.tide.temperatures, aes(x = factor(Temp_Treatment), y = Temp, fill = pH_Treatment)) +
  geom_boxplot() +
  labs(
    x = "Temp Treatment",
    y = "Temperature (°C)",
    fill = "pH Treatment"
  ) +
  ggtitle("Mean Temperature in Treatment Tanks HOBO Logger") +
  scale_fill_manual(values = c("Ambient" = "orange", "Low" = "cyan3")) +  # Specify colors
  theme_minimal()

# Create the box and whisker plot without outliers
ggplot(high.tide.temperatures, aes(x = factor(Temp_Treatment), y = Temp, fill = pH_Treatment)) +
  geom_boxplot(outlier.shape = NA) +  # Remove outliers
  labs(
    x = "Temp Treatment",
    y = "Temperature (°C)",
    fill = "pH Treatment"
  ) +
  ggtitle("Mean Temperature in Treatment Tanks HOBO Logger (no outliers)") +
  scale_fill_manual(values = c("Ambient" = "orange", "Low" = "cyan3")) +  # Specify colors
  theme_minimal()

```


