---
title: "Study Site Environmental Parameters"
output:
  pdf_document: default
  html_document: default
date: "2023-08-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)
library(tidyverse)
library(ggplot2)

```

 
Temp and Salinity Data from UCSD Shore Stations 1924-2023
 
```{r}

newport.temp <- read_csv(here("Data", "Site_Data", "NewportBeach_TEMP_1924-2023.csv"), skip=44)

# Filter data where TEMP_FLAG is either NaN or 1
filtered_data <- newport.temp %>%
  filter(TEMP_FLAG == 0)

# Convert YEAR and MONTH to a date format
filtered_data <- filtered_data %>%
  mutate(DATE = ymd(paste(YEAR, MONTH, DAY))) %>% 
  select(DATE, SURF_TEMP_C, TEMP_FLAG)

# Create a time series plot using ggplot
ggplot(data = filtered_data) +
  geom_line(aes(x = DATE, y = SURF_TEMP_C), color = "orange2") +
  labs(x = "Date", y = "Surface Temperature (°C)", title = "Time Series of Surface Temperature") +
  theme_minimal()
```
```{r}

study.date.temp <- read_csv(here("Data", "Site_Data", "newport-pier-automated-station-study-site-sst-jul-26-2022-aug-16-2022.csv"))[-1,]

study.date.temp <- study.date.temp %>% 
  mutate(time=ymd_hms(time))


# Define the target date (August 16, 2022)
target_date <- as.Date("2022-08-16")

# Calculate the start date (3 weeks prior to the target date)
start_date <- target_date - lubridate::weeks(2)

# Filter the data for the specified date range
study_date_data <- study.date.temp %>%
  filter(time >= start_date & time < target_date)

# Filter out NA and 0 values in sea_water_temperature column
study_date_data <- study_date_data %>%
  mutate(sea_water_temperature = as.numeric(sea_water_temperature)) %>% 
  filter(!is.na(sea_water_temperature) & sea_water_temperature != 0)

# Calculate the mean sea_water_temperature and count (N)
mean_temp <- mean(study_date_data$sea_water_temperature, na.rm = TRUE)
sd_temp <- sd(study_date_data$sea_water_temperature, na.rm = TRUE)
count_temp <- nrow(study_date_data)
  
cat("Mean Sea Water Temperature:", mean_temp, "\n")
cat("Standard Deviation:", sd_temp, "\n")
cat("N:", count_temp, "\n")

```


```{r}

newport.salt <- read_csv(here("Data", "Site_Data", "NewportBeach_SALT_1924-2023.csv"), skip=44)

# Filter data where TEMP_FLAG is either NaN or 1
filtered_data <- newport.salt %>%
  filter(SALT_FLAG == 0)

# Convert YEAR and MONTH to a date format
filtered_data <- filtered_data %>%
  mutate(DATE = ymd(paste(YEAR, MONTH, DAY))) %>% 
  select(DATE, SALINITY_PSU, SALT_FLAG)

ggplot(data = filtered_data) +
  geom_line(aes(x = DATE, y = SALINITY_PSU), color = "yellow2") +
  labs(x = "Date", y = "Seawater Salinity (PSU)", title = "Time Series of Salinity") +
  theme_minimal()
  
```

pH Data from Newport Beach Pier Automated Shore Station

```{r}

# Read the "newport.pH" dataset
newport.pH <- read_csv(here("Data", "Site_Data", "NewportBeach_PH_2018-2023.csv"))

# Remove the first row of data and select for pH corrected data
newport.pH <- newport.pH[-1, ] %>% 
  mutate(pH = sea_water_ph_reported_on_total_scale_salinity_corrected) %>% 
  select(time, pH)

# Convert the "Time" column to POSIXct
newport.pH <- newport.pH %>%
  mutate(Time = ymd_hms(time)) %>% 
  select(Time, pH)

# Create a time series plot using ggplot
ggplot(data = newport.pH) +
  geom_line(aes(x = Time, y = pH), color = "blue") +
  labs(x = "Time", y = "pH", title = "Time Series of pH") +
  theme_minimal()


```

Newport Beach pH Binned Weekly Summary

```{r}

# Read the CSV file 
weekly_pH_data <- read_csv(here("Data", "Site_Data", "NewportBeach_PH_2018-2023_pH_Binned_weeks.csv"))

# Create a ggplot visualization
ggplot(weekly_pH_data, aes(x = `Start date`, y = Mean)) +
  geom_line(color = "blue", size = 1) +
  geom_errorbar(aes(ymin = Min, ymax = Max), width = 0.2, color = "red") +
  labs(x = "Week", y = "pH", title = "Weekly pH Data") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```



```{r}

mean_pH_Data <- weekly_pH_data %>% 
  select(Mean) %>% 
  summarise(mean_pH=mean(as.numeric(Mean), na.rm=TRUE))

print(mean_pH_Data)
```

